AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Type: String
  CertificateArn:
    Type: String
  Domain:
    Type: String
  SubDomain:
    Type: String
Resources:
  OAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: AccessCloudFrontToS3
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  S3BucketOAIPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: S3Bucket
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        - Action: s3:GetObject
          Effect: Allow
          Resource: !Join ['', ['arn:aws:s3:::', !Ref BucketName, /*]]
          Principal:
            CanonicalUser: !GetAtt OAI.S3CanonicalUserId
  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !Join ['', [!Ref BucketName, .s3.ap-northeast-2.amazonaws.com]]
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', [origin-access-identity/cloudfront/, !Ref OAI]]
        DefaultCacheBehavior:
          MinTTL: 0
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        Aliases:
          - !Join ['', [!Ref SubDomain, '.', !Ref Domain]]
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        HttpVersion: http2
  CNDDns:
    Type: AWS::Route53::RecordSet
    DependsOn: CDN
    Properties:
      AliasTarget:
        DNSName: !GetAtt CDN.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Join ['', [!Ref Domain, '.']]
      Name: !Join ['', [!Ref SubDomain, '.', !Ref Domain]]
      Type: A
